let EventObj = {  
   "PTIEvent":{  
      "AttributeID":"98",
      "AttributeName":"Temp pti",
      "Attributes":{  
         "Attribute":{  
            "_YMBrand":"",
            "Brand":"",
            "CaseType":"Bag",
            "CaseTypeGDSN":"BAG",
            "City":"",
            "Commodity":"Mushroom",
            "CountryofOrginGDSN":"USA",
            "CountryofOrigin":"UNITED STATES",
            "DepthofCase":"5",
            "DepthofCaseUOM":"FT",
            "Description":"Fresh and Clean",
            "Grade":"US #1",
            "GrossWeightofCase":"5",
            "GrossWeightofCaseUOM":"KB",
            "GrowingMethod":"Organic",
            "GrowingRegion":"",
            "GS1PrefixCode":"",
            "GTIN":"14563720000000",
            "HeightofCase":"25",
            "HeightofCaseUOM":"CM",
            "InnerPackSize":"5.0",
            "InnerPackSizeUOM":"KG",
            "InnerPackStyle":"Bag",
            "InnerPackStyleGDSN":"BAG",
            "ItemNumber":"0",
            "Lot":"T34WQ",
            "NetWeightofCase":"5",
            "NetWeightofCaseUOM":"BU",
            "PackDate":"12\/04\/2017",
            "Packer":"",
            "PackLevel":"1",
            "PalletHigh":"",
            "PalletTie":"",
            "PLU":"6587",
            "PrintLabel":"4X2RPC",
            "Quantityofitemsincase":"5",
            "QuantityofLabelsPrinted":"1",
            "RPCPackDate":"Dec04",
            "SizeGroup":"1",
            "State":"",
            "UPC":"98799628789",
            "UPCReference":"",
            "Variety":"Org Baby Bella",
            "WidthofCase":"52",
            "WidthofCaseUOM":"CM",
            "WorkerID":"SE19",
            "WorkerName":"Peter John",
            "YMProducerName":"",
            "YMProductID":"",
            "YMProductName":""
         }
      },
      "Codes":{  
         "devicename":"",
         "timestamp":"2017-12-04T14:40:58.3495882+05:30",
         "value":"145895804255MMU1"
      },
      "eventName":"PTI",
      "eventTime":"2017-12-04T14:40:58.4575944+05:30",
      "eventTimeZoneOffset":"05:30:00",
      "EventType":"Production",
      "ipAddress":"127.0.0.1",
      "lat":"155.00",
      "locationName":"Monterey Mushrooms, Inc.",
      "long":"-202.00",
      "onBehalfOf":"111",
      "processTime":"2017-12-04T14:40:58.4595945+05:30",
      "ptiClientVersion":"7.0",
      "RoRAttributes":null,
      "submittedBy":"111",
      "trackingCode":"14563720000000T34WQ1",
      "userName":"ptiuser@mm.com"
   }
};

module.exports = EventObj;