let EventObj = {  
   "PTIEvent":{  
      "Attributes":{  
         "Attribute":{  
            "CaseType":"Carton",
            "CaseTypeGDSN":"CT",
            "City":"",
            "Commodity":"APPLES",
            "CountryofOrginGDSN":"USA",
            "CountryofOrigin":"UNITED STATES",
            "DepthofCase":"20",
            "DepthofCaseUOM":"FT",
            "Description":"GTIN list test commodity",
            "Grade":"US Extra Fancy",
            "GrossWeightofCase":"10",
            "GrossWeightofCaseUOM":"KB",
            "GrowingMethod":"Greenhouse",
            "GrowingRegion":"",
            "GS1PrefixCode":"",
            "GTIN":"11234512340002",
            "HeightofCase":"17",
            "HeightofCaseUOM":"FT",
            "InnerPackSize":"25.0",
            "InnerPackSizeUOM":"LB",
            "InnerPackStyle":"Bag",
            "InnerPackStyleGDSN":"BAG",
            "ItemNumber":"0",
            "Lot":"JTW176",
            "NetWeightofCase":"50",
            "NetWeightofCaseUOM":"KG",
            "Packer":"",
            "PackLevel":"1",
            "PalletHigh":"20",
            "PalletTie":"10",
            "PLU":"52365236",
            "PrintLabel":"4X2RPC",
            "Quantityofitemsincase":"25",
            "QuantityofLabelsPrinted":"1",
            "RPCPackDate":"Jul12",
            "SizeGroup":"10",
            "State":"",
            "UPC":"",
            "UPCReference":"",
            "Variety":"Jazz",
            "WidthofCase":"100",
            "WidthofCaseUOM":"FT",
            "WorkerID":"R086",
            "WorkerName":"Kumar",
            "YMProducerName":"",
            "YMProductID":"",
            "YMProductName":""
         }
      },
      "Codes":{  
         "devicename":"",
         "timestamp":"2017-12-07T15:44:27.5761847+05:30",
         "value":"729334737341RIV5"
      },
      "EventName":"PTI",
      "EventTime":"2017-12-07T15:44:27.6301878+05:30",
      "EventTimeZoneOffset":"05:30:00",
      "EventType":"Production",
      "IpAddress":"127.0.0.1",
      "Lat":"155.00",
      "LocationName":"River Farms",
      "Long":"-202.00",
      "OnBehalfOf":"679",
      "ProcessTime":"2017-12-07T15:44:27.6321879+05:30",
      "ProducerId":"679",
      "PtiClientVersion":"7.0",
      "RoRAttributes":null,
      "SubmittedBy":"679",
      "TrackingCode":"11234512340002JTW1761",
      "UserName":"riversupport@gmail.com"
   }
};

module.exports = EventObj;