
let GTINDBList = {
  "GTINRecords": {
    "GTINRecord": [
      {
        "PackLevel": "1",
        "ItemNo": "1",
        "RefNo": "101",
        "Description": "spice",
        "Commodity": "Pepper",
        "Variety": "Red",
        "CountryofOrigin": "INDIA",
        "CountryofOriginGDSN": "IN",
        "Grade": "US Fancy",
        "GrowingMethod": "Conventional",
        "NetWeightofCase": "10",
        "NetWeightofCaseUOM": "KG",
        "CaseType": "Carton",
        "CaseTypeGDSN": "CT",
        "Quantityofitemsincase": "10",
        "InnerPackStyle": "Bulk",
        "InnerPackStyleGDSN": "BLK",
        "SizeGroup": "1",
        "GS1PrefixName": "River Farms",
        "PLUNumber": "1234",
        "UPCNumber": "23456789012",
        "GTIN": "11234567650019",
        "EffectiveDateofChange": "2017-11-23 09:21:52 UTC",
        "DescriptionLine1": "Pepper",
        "DescriptionLine2": "Red",
        "PackLine1": "10 KG CT",
        "PackLine2": "1",
        "PackLine3": "Pepper Red 10 KG CT 1",
        "PackLine4": "Pepper Red",
        "PackLine5": "10 KG CT 1",
        "PackLine6": "Pepper Red",
        "PackLine7": "10 KG CT 1"
      },
      {
        "PackLevel": "1",
        "ItemNo": "2",
        "RefNo": "102",
        "Description": "Anaheim  1/4 Ctn Bushel",
        "Commodity": "ORANGES",
        "Variety": "Blood",
        "CountryofOrigin": "MEXICO",
        "CountryofOriginGDSN": "MEXICO",
        "Grade": "US #1",
        "GrowingMethod": "Conventional",
        "NetWeightofCase": "789321",
        "CaseType": "Carton",
        "CaseTypeGDSN": "CT",
        "Quantityofitemsincase": "5",
        "InnerPackStyle": "Bundle",
        "InnerPackStyleGDSN": "BD",
        "InnerPackSize": "5.0",
        "InnerPackSizeUOM": "GA",
        "SizeGroup": "1",
        "HeightofCase": "15",
        "HeightUOM": "CM",
        "WidthofCase": "12",
        "WidthofCaseUOM": "CM",
        "DepthofCase": "5",
        "DepthofCaseUOM": "CM",
        "GrossWeightofCase": "5",
        "GrossWeightofCaseUOM": "KB",
        "GS1PrefixName": "River Farms",
        "PLUNumber": "25412",
        "UPCNumber": "112345123402",
        "GTIN": "11234567650026",
        "EffectiveDateofChange": "2017-11-23 09:21:52 UTC",
        "DescriptionLine1": "ORANGES",
        "DescriptionLine2": "Blood",
        "PackLine1": "789321 123654",
        "PackLine2": "5/25 GA Bundl",
        "PackLine3": "ORANGES Blood 789321 123654 5/25 GA Bundle",
        "PackLine4": "ORANGES Blood",
        "PackLine5": "789321 123654 5/25 GA Bundle",
        "PackLine6": "ORANGES Blood Test123",
        "PackLine7": "12CT/8.2 RPC/ Organic"
      },
      {
        "PackLevel": "1",
        "ItemNo": "3",
        "RefNo": "103",
        "Description": "test",
        "Commodity": "BEANS",
        "Variety": "Green Bean",
        "CountryofOrigin": "BAHRAIN",
        "CountryofOriginGDSN": "BH",
        "Grade": "US #1",
        "GrowingMethod": "Conventional",
        "GS1PrefixName": "River Farms",
        "GTIN": "11234567650033",
        "EffectiveDateofChange": "2017-11-23 09:21:52 UTC",
        "DescriptionLine1": "BEANS",
        "DescriptionLine2": "Green Bean",
        "YMProductName": "BEANS Green Bean"
      },
      {
        "PackLevel": "1",
        "ItemNo": "4",
        "RefNo": "104",
        "Description": "Almonds Almonds",
        "Commodity": "ALMONDS   ",
        "Variety": "Retailer Assigned",
        "CountryofOrigin": "UNITED STATES",
        "CountryofOriginGDSN": "USA",
        "Grade": "US #1",
        "GrowingMethod": "Organic",
        "NetWeightofCase": "5",
        "NetWeightofCaseUOM": "LB",
        "CaseType": "Box",
        "CaseTypeGDSN": "BOX",
        "Quantityofitemsincase": "5",
        "InnerPackStyle": "Clamshell",
        "InnerPackStyleGDSN": "CMS",
        "InnerPackSizeUOM": "LB",
        "GS1PrefixName": "River Farms",
        "GTIN": "11234567650040",
        "EffectiveDateofChange": "2017-11-23 09:21:53 UTC",
        "DescriptionLine1": "ALMONDS",
        "DescriptionLine2": "Retailer Assign",
        "PackLine1": "5 LB BOX",
        "PackLine2": "5  LB Clamshe",
        "PackLine3": "ALMONDS Retailer Assigned 5 LB BOX 5  LB Clamshell",
        "PackLine4": "ALMONDS Retailer Assigned",
        "PackLine5": "5 LB BOX 5  LB Clamshell",
        "PackLine6": "ALMONDS Retailer Assi",
        "PackLine7": "5 LB BOX 5  LB Clamsh",
        "YMProductName": "ALMONDS Retailer Assigned"
      },
      {
        "PackLevel": "1",
        "ItemNo": "5",
        "RefNo": "105",
        "Description": "Red Bananas",
        "Commodity": "BANANAS",
        "Variety": "Red",
        "CountryofOrigin": "UNITED STATES",
        "CountryofOriginGDSN": "USA",
        "Grade": "US #1",
        "GrowingMethod": "Conventional",
        "NetWeightofCase": "50",
        "NetWeightofCaseUOM": "KG",
        "CaseType": "Bin",
        "CaseTypeGDSN": "BIN",
        "InnerPackSize": "10.0",
        "InnerPackSizeUOM": "KG",
        "SizeGroup": "5",
        "HeightofCase": "8",
        "HeightUOM": "IN",
        "WidthofCase": "5",
        "WidthofCaseUOM": "IN",
        "GS1PrefixName": "River Farms",
        "PLUNumber": "1234",
        "UPCNumber": "987654321011",
        "GTIN": "11234567650057",
        "EffectiveDateofChange": "2017-11-23 09:26:37 UTC",
        "DescriptionLine1": "BANANAS",
        "DescriptionLine2": "Red",
        "PackLine1": "50 KG BIN",
        "PackLine2": "5",
        "PackLine3": "BANANAS Red 50 KG BIN 5",
        "PackLine4": "BANANAS Red",
        "PackLine5": "50 KG BIN 5",
        "PackLine6": "BANANAS Red",
        "PackLine7": "50 KG BIN 5",
        "YMProductName": "BANANAS Red"
      },
{
        "PackLevel": "1",
        "ItemNo": "0",
        "RefNo": "100",
        "Description": "GTIN list test commodity",
        "Commodity": "APPLES",
        "Variety": "Jazz",
        "CountryofOrigin": "UNITED STATES",
        "CountryofOriginGDSN": "USA",
        "Grade": "US Extra Fancy",
        "GrowingMethod": "Greenhouse",
        "NetWeightofCase": "50",
        "NetWeightofCaseUOM": "KG",
        "CaseType": "Carton",
        "CaseTypeGDSN": "CT",
        "Quantityofitemsincase": "25",
        "InnerPackStyle": "Bag",
        "InnerPackStyleGDSN": "BAG",
        "InnerPackSize": "25.0",
        "InnerPackSizeUOM": "LB",
        "SizeGroup": "10",
        "HeightofCase": "17",
        "HeightUOM": "FT",
        "WidthofCase": "100",
        "WidthofCaseUOM": "FT",
        "DepthofCase": "20",
        "DepthofCaseUOM": "FT",
        "GrossWeightofCase": "10",
        "GrossWeightofCaseUOM": "KB",
        "PalletTie": "10",
        "PalletHigh": "20",
        "GS1PrefixName": "River Farms v2",
        "PLUNumber": "523652",
        "UPCNumber": "89325476124",
        "GTIN": "11234512340002",
        "EffectiveDateofChange": "2017-10-31 10:12:13 UTC",
        "DescriptionLine1": "APPLES",
        "DescriptionLine2": "Jazz",
        "PackLine1": "50 KG CT",
        "PackLine2": "25/25 LB Bag",
        "PackLine3": "APPLES Jazz 50 KG CT 25/25 LB Bag",
        "PackLine4": "APPLES Jazz",
        "PackLine5": "50 KG CT 25/25 LB Bag",
        "PackLine6": "APPLES Jazz",
        "PackLine7": "50 KG CT 25/25 LB B"
      },
      {
        "PackLevel": "1",
        "ItemNo": "1",
        "RefNo": "101",
        "Description": "BELGIAN/RED",
        "Commodity": "BELGIAN ENDIVE (WITLOOF CHICORY)",
        "Variety": "Red",
        "CountryofOrigin": "BARBADOS",
        "CountryofOriginGDSN": "BB",
        "Grade": "US #2",
        "GrowingMethod": "Greenhouse",
        "NetWeightofCase": "2",
        "CaseType": "Bin",
        "CaseTypeGDSN": "BIN",
        "Quantityofitemsincase": "2",
        "InnerPackStyle": "Carton",
        "InnerPackStyleGDSN": "CT",
        "InnerPackSize": "2.0",
        "InnerPackSizeUOM": "LB",
        "HeightofCase": "2",
        "WidthofCase": "1",
        "WidthofCaseUOM": "CM",
        "DepthofCase": "1",
        "DepthofCaseUOM": "CM",
        "GrossWeightofCase": "1",
        "GrossWeightofCaseUOM": "BU",
        "GS1PrefixName": "River Farms v2",
        "GTIN": "11234512340019",
        "EffectiveDateofChange": "2017-10-31 10:12:13 UTC",
        "DescriptionLine1": "BELGIAN ENDIVE ",
        "DescriptionLine2": "Red",
        "PackLine1": "BIN",
        "PackLine2": "2.5/1.7 LB Ca",
        "PackLine3": "BELGIAN ENDIVE (WITLOOF CHICORY) Red BIN 2.5/1.7 LB Carton",
        "PackLine4": "BELGIAN ENDIVE (WITLOOF CHICORY) Red",
        "PackLine5": "BIN 2.5/1.7 LB Carton",
        "PackLine6": "BELGIAN ENDIVE (WI",
        "PackLine7": "BIN 2.5/1.7 LB Cart"
      },
      {
        "PackLevel": "1",
        "ItemNo": "2",
        "RefNo": "102",
        "Description": "#2 Jazz/Apples",
        "Commodity": "APPLES",
        "Variety": "Jazz",
        "CountryofOrigin": "UNITED STATES",
        "CountryofOriginGDSN": "USA",
        "Grade": "US Extra Fancy",
        "GrowingMethod": "Greenhouse",
        "NetWeightofCase": "50",
        "NetWeightofCaseUOM": "KG",
        "CaseType": "Carton",
        "CaseTypeGDSN": "CT",
        "Quantityofitemsincase": "25",
        "InnerPackStyle": "Bag",
        "InnerPackStyleGDSN": "BAG",
        "InnerPackSize": "25.0",
        "InnerPackSizeUOM": "LB",
        "SizeGroup": "10",
        "HeightofCase": "17",
        "HeightUOM": "FT",
        "WidthofCase": "100",
        "WidthofCaseUOM": "FT",
        "DepthofCase": "20",
        "DepthofCaseUOM": "FT",
        "GrossWeightofCase": "10",
        "GrossWeightofCaseUOM": "KB",
        "PalletTie": "10",
        "PalletHigh": "20",
        "GS1PrefixName": "River Farms v2",
        "PLUNumber": "52365236",
        "GTIN": "11234512340026",
        "EffectiveDateofChange": "2017-10-31 10:12:13 UTC",
        "PackLine1": "50 KG CT",
        "PackLine2": "25/25 LB Bag",
        "PackLine3": "APPLES Jazz 50 KG CT 25/25 LB Bag",
        "PackLine4": "APPLES Jazz",
        "PackLine5": "50 KG CT 25/25 LB Bag",
        "PackLine6": "APPLES Jazz",
        "PackLine7": "50 KG CT 25/25 LB B"
      },
{
        "PackLevel": "1",
        "ItemNo": "0",
        "RefNo": "100",
        "Description": "#0 Bean Sprouts",
        "Commodity": "BEAN SPROUTS",
        "Variety": "(Mung Bean Sprouts)",
        "GS1PrefixName": "River Brand",
        "GTIN": "19876536600001",
        "EffectiveDateofChange": "2017-09-06 11:20:09 UTC",
        "DescriptionLine1": "BEAN SPROUTS",
        "DescriptionLine2": "(Mung Bean Spro",
        "YMProductName": "BEAN SPROUTS (Mung Bean Sprouts)"
      },
      {
        "PackLevel": "1",
        "ItemNo": "0",
        "RefNo": "100",
        "Description": "#0 Bean Sprouts",
        "Commodity": "BEAN SPROUTS",
        "Variety": "(Mung Bean Sprouts)",
        "GS1PrefixName": "River Brand",
        "GTIN": "19876536600001",
        "EffectiveDateofChange": "2017-09-06 11:20:07 UTC",
        "DescriptionLine1": "BEAN SPROUTS",
        "DescriptionLine2": "(Mung Bean Spro",
        "YMProductName": "BEAN SPROUTS (Mung Bean Sprouts)"
      }
    ]
  }
};

module.exports = GTINDBList;